version: "3.7"
services:
  bitcoin:
    image: renproject/bitcoin:localnet
    entrypoint:
      - "./root/run.sh"
      - "mmjwW62DSSWbHuMmRTqUdWd5ABGStniygb"

  zcash:
    image: renproject/zcash:localnet
    entrypoint:
      - "./root/run.sh"
      - "tmExAcmdSvXsNodpDRbg6LAMUqeVyMVtikL"
    
  bcash:
    image: renproject/bcash:localnet
    entrypoint:
      - "./root/run.sh"
      - "qzjwrklk7mr5qnhp66z7vy50gj0tnj3xxgl5ztpnsx"
    
  ethereum:
    image: renproject/parity:localnet

  mercury: 
    build:
      context: ./mercury
      args:
        BTC_RPC_URL: 'http://bitcoin:18443'
        ZEC_RPC_URL: 'http://zcash:18232'
        BCH_RPC_URL: 'http://bcash:18443'
        ETH_RPC_URL: 'http://ethereum:8545'
    image: mercury:latest
    ports: 
      - "5000:5000"